service: notifications
frameworkVersion: '3.17.0'
useDotenv: true

params: ${file(./environment/params.yml)}

provider: ${file(./environment/provider.yml)}

plugins:
    - serverless-offline
    - serverless-prune-plugin

custom:
    serverless-offline:
        host: 0.0.0.0
        httpPort: 3008
    prune:
        automatic: true
        number: 3

package:
    individually: true
    exclude:
      - ./.git/**
      - ./.serverless/**
      - ./node_modules/**
      - ./pkg/**
      - ./bootstrap/**
      - ./cmd/**
      - ./.dockers/**
      - ./.githooks/**
      - ./bin/**

functions:
  notifications-create:
    description: Create a new notification
    handler: bin/notification-create
    events:
      - http:
          path: /notifications
          method: post
          cors: true
    package:
      patterns:
        - ./bin/notification-create
  notifications-getall:
    description:  Get all the products notifications  
    handler: bin/notification-create
    events:
      - http:
          path: /notifications
          method: get
          cors: true
    package:
      patterns:
        - ./bin/notification-create